I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 248, in script
    with Shake((0, 0, 0, 0), 1.0, dist=10)
  File "game/script.rpy", line 248, in <module>
    with Shake((0, 0, 0, 0), 1.0, dist=10)
NameError: name 'Shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 248, in script
    with Shake((0, 0, 0, 0), 1.0, dist=10)
  File "C:\coding\renpy-8.0.3-sdk.7z\renpy-8.0.3-sdk\renpy\ast.py", line 1651, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\coding\renpy-8.0.3-sdk.7z\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\coding\renpy-8.0.3-sdk.7z\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 248, in <module>
    with Shake((0, 0, 0, 0), 1.0, dist=10)
NameError: name 'Shake' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
异世界的雪与奇迹 
Sat Jun 10 23:19:40 2023
